### PR TITLE
Riyad1

### PR DESCRIPTION
**Pull request by riyadvaliyev**
Created and updated all the classes in Conversation use case (including all the layers)

### CODE REVIEW

**Review by taml5 — APPROVED** [review]
Great work!

**Comment by Accusamus2065** [comment]
Don't merge into main yet. Can you create a new commit or pull request to delete the `awl.xml` you pushed under the `.idea` folder, or I can help you with it after my exams.

**Comment by taml5** [comment]
> Don't merge into main yet. Can you create a new commit or pull request to delete the `awl.xml` you pushed under the `.idea` folder, or I can help you with it after my exams.

Sorry I already merged, didn't notice `awl.xml`. I'll push a new branch to delete it now!

**Comment by Accusamus2065** [comment]
> > Don't merge into main yet. Can you create a new commit or pull request to delete the `awl.xml` you pushed under the `.idea` folder, or I can help you with it after my exams.
> 
> Sorry I already merged, didn't notice `awl.xml`. I'll push a new branch to delete it now!

No worries, seems like you only approved but not merge the branch yet on my end.

**Pull request merged**
